name: Build APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v4


      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            python3-pip \
            python3-setuptools \
            python3-virtualenv \
            git \
            zip \
            unzip \
            wget \
            openjdk-17-jdk \
            autoconf \
            libtool \
            pkg-config \
            zlib1g-dev \
            libffi-dev \
            libssl-dev


      - name: Install Buildozer
        run: |
          pip install --user git+https://github.com/kivy/buildozer.git
          pip install --user cython==0.29.36


      - name: Install Android SDK command line tools
        run: |
          mkdir -p $HOME/.buildozer/android/platform/android-sdk/cmdline-tools

          cd $HOME/.buildozer/android/platform/android-sdk/cmdline-tools

          wget https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip

          unzip commandlinetools-linux-11076708_latest.zip

          mv cmdline-tools latest


          echo "ANDROID_HOME=$HOME/.buildozer/android/platform/android-sdk" >> $GITHUB_ENV
          echo "ANDROID_SDK_ROOT=$HOME/.buildozer/android/platform/android-sdk" >> $GITHUB_ENV

          echo "$HOME/.buildozer/android/platform/android-sdk/cmdline-tools/latest/bin" >> $GITHUB_PATH


      - name: Fix sdkmanager path for Buildozer
        run: |
          mkdir -p $ANDROID_SDK_ROOT/tools/bin

          ln -sf \
          $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager \
          $ANDROID_SDK_ROOT/tools/bin/sdkmanager

          ls -la $ANDROID_SDK_ROOT/tools/bin


      - name: Accept SDK licenses and install packages
        run: |
          yes | sdkmanager --licenses --sdk_root=$ANDROID_SDK_ROOT

          sdkmanager --sdk_root=$ANDROID_SDK_ROOT \
          "platform-tools" \
          "platforms;android-35" \
          "build-tools;35.0.0"


      - name: Build APK
        run: |
          buildozer android debug


      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: resume-builder-apk
          path: bin/*.apk
