name: Build Android APK

on:
  push:
    branches:
      - main

  workflow_dispatch:


jobs:
  build:

    runs-on: ubuntu-22.04


    steps:

      - name: Checkout
        uses: actions/checkout@v4


      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"


      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"


      - name: Install Linux dependencies
        run: |

          sudo apt update

          sudo apt install -y \
          git \
          zip \
          unzip \
          openjdk-17-jdk \
          autoconf \
          automake \
          libtool \
          pkg-config \
          zlib1g-dev \
          libffi-dev \
          libssl-dev \
          cmake


      - name: Install Buildozer

        run: |

          pip install --upgrade pip

          pip install setuptools

          pip install cython==0.29.36

          pip install buildozer==1.5.0



      - name: Cache Buildozer

        uses: actions/cache@v4

        with:

          path: |

            ~/.buildozer

            .buildozer


          key: buildozer-cache-${{ hashFiles('buildozer.spec') }}

          restore-keys: |

            buildozer-cache-



      - name: Accept Android licenses

        run: |

          mkdir -p ~/.android

          touch ~/.android/repositories.cfg

          yes | buildozer android update


      - name: Build APK

        run: |

          buildozer -v android debug



      - name: Upload APK

        uses: actions/upload-artifact@v4

        with:

          name: resume-builder-apk

          path: bin/*.apk
