name: Build Android APK

on:
  push:
    branches:
      - main
  workflow_dispatch:


jobs:
  build:

    runs-on: ubuntu-22.04

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4


      - name: Setup Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"


      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"


      - name: Install system dependencies
        run: |
          sudo apt update

          sudo apt install -y \
          autoconf \
          automake \
          libtool \
          libtool-bin \
          pkg-config \
          build-essential \
          git \
          zip \
          unzip \
          openjdk-17-jdk \
          libffi-dev \
          libssl-dev \
          zlib1g-dev \
          libsdl2-dev \
          libsdl2-image-dev \
          libsdl2-mixer-dev \
          libsdl2-ttf-dev \
          libportmidi-dev \
          libswscale-dev \
          libavformat-dev \
          libavcodec-dev


      - name: Install Buildozer
        run: |

          python -m pip install --upgrade pip

          pip install \
          buildozer==1.5.0 \
          cython==0.29.36 \
          setuptools


      - name: Cache Buildozer
        uses: actions/cache@v4
        with:

          path: |
            ~/.buildozer
            .buildozer

          key: buildozer-${{ runner.os }}-${{ hashFiles('buildozer.spec') }}

          restore-keys: |
            buildozer-${{ runner.os }}-


      - name: Prepare python-for-android
        run: |

          buildozer android p4a --help || true



      - name: Remove broken ReportLab recipe

        run: |

          P4A_DIR=$(find ~/.buildozer -type d -name "python-for-android" | head -1)

          echo "P4A PATH:"
          echo $P4A_DIR


          if [ -d "$P4A_DIR/pythonforandroid/recipes/reportlab" ]; then

              rm -rf "$P4A_DIR/pythonforandroid/recipes/reportlab"

              echo "ReportLab recipe removed"

          else

              echo "ReportLab recipe not found"

          fi



      - name: Build APK

        env:

          ANDROID_NDK_VERSION: "25b"

        run: |

          yes | buildozer -v android debug



      - name: Upload APK

        uses: actions/upload-artifact@v4

        with:

          name: resume-builder-apk

          path: bin/*.apk
